# <center>Python - Numpy - Practice <a class="tocSkip"></center>
# <center>QTM 350: Data Science Computing <a class="tocSkip"></center>    
# <center>Davi Moreira <a class="tocSkip"></center>

## Introduction <a class="tocSkip">
<hr>

<center>
<div>
<img src="https://raw.githubusercontent.com/davi-moreira/2024S_dsc_emory_qtm_350/main/lecture_material/material-topic-03/img/py4ds.png" width="200"/>
</div>
</center>


This topic material is based on the [Python Programming for Data Science](https://www.tomasbeuzen.com/python-programming-for-data-science/README.html) book and adapted for our purposes in the course.

## Exercise

Import numpy under the alias `np`.

In [ ]:
# Your answer here.

## Exercise

Create the following arrays:

1. Create an array of 5 zeros.
2. Create an array of 10 ones.
3. Create an array of 5 3.141s.
4. Create an array of the integers 1 to 20.
5. Create a 5 x 5 matrix of ones with a dtype `int`.

In [ ]:
# Your answer here.

## Exercise

Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [ ]:
# Your answer here.

## Exercise

Create an array of 20 linearly spaced numbers between 1 and 10.

In [ ]:
# Your answer here.

## Exercise

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [ ]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)

```python
20
```

In [ ]:
# Your answer here.

```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [ ]:
# Your answer here.

```python
array([ 6,  7,  8,  9, 10])
```

In [ ]:
# Your answer here.

```python
array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])
```

In [ ]:
# Your answer here.

```python
array([[ 8,  9],
       [13, 14]])
```

In [ ]:
# Your answer here.

## Exercise

Calculate the sum of all the numbers in `a`.

In [ ]:
# Your answer here.

## Exercise

Calculate the sum of each row in `a`.

In [ ]:
# Your answer here.

## Exercise

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [ ]:
# Your answer here.

## Exercise

Find the location of the minimum value in the following array `b`:

In [ ]:
np.random.seed(123)
b = np.random.randn(10)
b

In [ ]:
# Your answer here.

## Exercise

Find the location of the maximum value in the following 2D array `c` (hint: there are many ways to do this question, but a quick search on stackoverflow.com will typically help you find the optimum solution for a problem, for example see [post](https://stackoverflow.com/questions/3584243/get-the-position-of-the-biggest-item-in-a-multi-dimensional-numpy-array)):

In [ ]:
np.random.seed(123)
c = np.random.randn(3, 2)
c

In [ ]:
# Your answer here.

In [1]:
!jupyter nbconvert _06-py-numpy-practice.ipynb --to html --template classic --output 06-py-numpy-practice.html

[NbConvertApp] Converting notebook _06-py-numpy-practice.ipynb to html
[NbConvertApp] Writing 291872 bytes to 06-py-numpy-practice.html


# <center>Have fun!<a class="tocSkip"></center>