# <center>Python - Numpy - Practice Solutions <a class="tocSkip"></center>
# <center>QTM 350: Data Science Computing <a class="tocSkip"></center>    
# <center>Davi Moreira <a class="tocSkip"></center>

## Introduction <a class="tocSkip">
<hr>

<center>
<div>
<img src="https://raw.githubusercontent.com/davi-moreira/2024S_dsc_emory_qtm_350/main/lecture_material/material-topic-03/img/py4ds.png" width="200"/>
</div>
</center>


This topic material is based on the [Python Programming for Data Science](https://www.tomasbeuzen.com/python-programming-for-data-science/README.html) book and adapted for our purposes in the course.

## Exercise

Import numpy under the alias `np`.

In [1]:
import numpy as np

## Exercise

Create the following arrays:

1. Create an array of 5 zeros.
2. Create an array of 10 ones.
3. Create an array of 5 3.141s.
4. Create an array of the integers 1 to 20.
5. Create a 5 x 5 matrix of ones with a dtype `int`.

In [2]:
print(np.zeros(5))
print(np.ones(10))
print(np.full(5, 3.141))
print(np.array(range(21)))
print(np.ones((5, 5), dtype=int))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[3.141 3.141 3.141 3.141 3.141]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Exercise

Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [3]:
x = np.random.randn(3, 3, 3)
x

array([[[ 0.2564968 ,  2.55317243,  0.54485001],
        [-1.99522138,  0.86862483, -0.51887437],
        [ 0.56770014, -1.9148608 ,  0.91908687]],

       [[ 1.13506658, -0.38908093,  0.27064298],
        [-0.29785048, -0.18973305,  0.34921984],
        [ 0.93683315,  0.44742019, -0.35597381]],

       [[-1.21183078,  1.30004056, -1.08822641],
        [-0.04281199, -1.72461099, -0.68070007],
        [ 0.96356923, -0.51768483,  1.93929991]]])

In [4]:
x.reshape(-1) # or x.reshape(27)

array([ 0.2564968 ,  2.55317243,  0.54485001, -1.99522138,  0.86862483,
       -0.51887437,  0.56770014, -1.9148608 ,  0.91908687,  1.13506658,
       -0.38908093,  0.27064298, -0.29785048, -0.18973305,  0.34921984,
        0.93683315,  0.44742019, -0.35597381, -1.21183078,  1.30004056,
       -1.08822641, -0.04281199, -1.72461099, -0.68070007,  0.96356923,
       -0.51768483,  1.93929991])

## Exercise

Create an array of 20 linearly spaced numbers between 1 and 10.

In [5]:
np.linspace(1, 10, 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

## Exercise

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [26]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [27]:
a[3,4]

20

In [28]:
a[1:,3:]

array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])

In [29]:
a[1,:]

array([ 6,  7,  8,  9, 10])

```python
array([ 6,  7,  8,  9, 10])
```

In [30]:
a[1:3,2:4]

array([[ 8,  9],
       [13, 14]])

```python
array([[ 8,  9],
       [13, 14]])
```

## Exercise

Calculate the sum of all the numbers in `a`.

In [18]:
a.sum()

325

## Exercise

Calculate the sum of each row in `a`.

In [19]:
a.sum(axis=1)

array([ 15,  40,  65,  90, 115])

## Exercise

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [20]:
a[a > a.mean()]

array([14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

## Exercise

Find the location of the minimum value in the following array `b`:

In [21]:
np.random.seed(123)
b = np.random.randn(10)
b

array([-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471, -0.57860025,
        1.65143654, -2.42667924, -0.42891263,  1.26593626, -0.8667404 ])

In [22]:
b.argmin()

6

## Exercise

Find the location of the maximum value in the following 2D array `c` (hint: there are many ways to do this question, but a quick search on stackoverflow.com will typically help you find the optimum solution for a problem, for example see [post](https://stackoverflow.com/questions/3584243/get-the-position-of-the-biggest-item-in-a-multi-dimensional-numpy-array)):

In [23]:
np.random.seed(123)
c = np.random.randn(3, 2)
c

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654]])

In [24]:
print(f"Location of maximum: {np.unravel_index(c.argmax(), c.shape)}")
print(f"   Value of maximum: {c.max():.2f}")

Location of maximum: (2, 1)
   Value of maximum: 1.65


In [31]:
!jupyter nbconvert _06-py-numpy-practice-solutions.ipynb --to html --template classic --output 06-py-numpy-practice-solutions.html

[NbConvertApp] Converting notebook _06-py-numpy-practice-solutions.ipynb to html
[NbConvertApp] Writing 298383 bytes to 06-py-numpy-practice-solutions.html


# <center>Have fun!<a class="tocSkip"></center>